### ISSUE TITLE
Support for LinkAccount card?

### ISSUE THREAD

**Issue by benedekh** [Accenture/alexia#50]
Hi, 

Does the SDK support user authentication, like LinkAccount card?

Regards,

Ben

**Comment by chrischang** [comment]
Hi @benedekh,

It looks like it does support LinkAccount card; however, it was not specified in the README.
It looks if card.type isn't specified, the type default to 'Simple'
If you wish to return the account linking card, you can do something like this...

```
if (!event.session.user.accessToken) {
      return {
        text: 'You must have your account linked to use this skill. Please use the Alexa app to link your Amazon account with your account.',
        card: {
          type: 'LinkAccount'
        },
        end: true
      }
    }
```
@Glogo can you verify?

**Comment by Glogo** [comment]
Yes, alexia supports all types of cards, since the whole card object is passed in request.
In addition, as @chrischang already mentioned, the default card type is `Simple`

See this code, responsible for the described behaviour: https://github.com/Accenture/alexia/blob/master/src/handle-request.js#L166-L174

**Comment by benedekh** [comment]
Thank you @chrischang and @Glogo for the help.
